services:
  backend:
    build:
      context: ./server
    ports:
      - "1323:1323"
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:1323

networks:
  app-network:
    driver: bridge
