name: CI/CD BookStore App

on:
  push:
    branches:
      - main
env:
  AZURE_CONTAINER_REGISTRY: ksiazkarnia.azurecr.io
  AZURE_CR_USERNAME: ${{ secrets.AZURE_CR_USERNAME }} 
  AZURE_CR_PASSWORD: ${{ secrets.AZURE_CR_PASSWORD }} 

  NEXT_PUBLIC_BACKEND_URL: http://backend:1323 
  NEXT_PUBLIC_BACKEND_URL_INTERNAL: http://backend:1323 

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ env.AZURE_CR_USERNAME }}
          password: ${{ env.AZURE_CR_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build ./BookStore/server -t ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-backend:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-backend:${{ github.sha }}

      - name: Build and push frontend image
        run: |
          docker build ./BookStore/client -t ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-frontend:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-frontend:${{ github.sha }}