name: CI/CD BookStore App

on:
  push:
    branches:
      - main
env:
  AZURE_CONTAINER_REGISTRY: ksiazkarnia.azurecr.io
  AZURE_CR_USERNAME: ${{ secrets.AZURE_CR_USERNAME }}  
  AZURE_CR_PASSWORD: ${{ secrets.AZURE_CR_PASSWORD }}  

  NEXT_PUBLIC_BACKEND_URL: http://backend:1323  
  NEXT_PUBLIC_BACKEND_URL_INTERNAL: http://backend:1323  

jobs:
  build_and_push_docker: # <-- To jest wcięte o 2 spacje
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ env.AZURE_CR_USERNAME }}
          password: ${{ env.AZURE_CR_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build ./BookStore/server -t ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-backend:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-backend:${{ github.sha }}
          docker tag ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-backend:${{ github.sha }} ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-backend:latest
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-backend:latest

      - name: Build and push frontend image
        run: |
          docker build ./BookStore/client -t ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-frontend:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-frontend:${{ github.sha }}
          # TUTAJ MIALES github.coSHA - ZMIEN NA github.sha
          docker tag ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-frontend:${{ github.sha }} ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-frontend:latest
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-frontend:latest

  deploy_to_azure: # <-- TO MUSI BYĆ WCIĘTE DOKŁADNIE TAK SAMO JAK build_and_push_docker
    runs-on: ubuntu-latest
    needs: build_and_push_docker

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

      - name: Deploy backend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ksiazkarnia-backend
          slot-name: 'production'
          images: '${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-backend:${{ github.sha }}'

      - name: Deploy frontend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ksiazkarnia-frontend
          slot-name: 'production'
          images: '${{ env.AZURE_CONTAINER_REGISTRY }}/bookstore-frontend:${{ github.sha }}'
          configuration-settings: |
            NEXT_PUBLIC_BACKEND_URL=${{ secrets.BACKEND_PUBLIC_URL }}
            NEXT_PUBLIC_BACKEND_URL_INTERNAL=${{ secrets.BACKEND_PUBLIC_URL }}